source 'https://rubygems.org'

gem 'cucumber', '~>1.3.9'
gem 'rspec'
gem 'selenium-webdriver'
gem 'pg'
gem 'activerecord', '~>4.0.4', :require => 'active_record'
gem 'capypage', '~>0.2.6'
gem 'rest-client'
gem 'database_cleaner'